apiVersion: v1
kind: Service
metadata:
  name: techtrends
  labels:
    app: techtrends
    tag: latest
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: techtrends
    tag: latest
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}