apiVersion: v1
kind: Service
metadata:
  name: techtrends
  labels:
    app: techtrends
  namespace: sandbox
spec:
  ports:
    - name: http
      port: 4111
      protocol: TCP
      targetPort: 3111
  type: ClusterIP